### ISSUE TITLE
py-lmdb maintenance

### ISSUE THREAD

**Issue by mklemm2** [jnwatson/py-lmdb#163]
Hi,

I've read your message regarding maintenance. Unfortunately, I don't speak C. I would be willing to help with documentation, looking into Issues and maybe provide more examples etc. Over the last couple of month I've really come to love lmdb and it would be a shame if it wasn't usable from my favorite language, anymore.

So, you still need someone to write code but if you find someone who would do that but is afraid of the rest, I'm willing to jump in.

Best regards,
Marcus

**Comment by dw** [comment]
Hi Markus!

Thanks for the offer -- definitely the biggest bugbear at present is looking after tickets, I find it the most draining aspect of keeping the project going.

There is a ton of new development work potentially in the pipeline -- landing the latest release of LMDB requires some deep magic on Windows to link the final build correctly due to their direct use of kernel symbols, and it looks like some new features are being planned, including page-level encryption.

Meanwhile it's just the tickets I feel really guilty about -- it feels really unfair to have people with reasonable easy questions waiting weeks for me to send a 1 liner reply :/

**Comment by dw** [comment]
I've started tidying up the Windows build process by moving it to AppVeyor, but this isn't completely done yet. Once the Windows build process is out of the way, minor development changes and fixes become much simpler to test, but presently it requires about a million different versions of Python and Visual Studio to be installed on a VM to work with usefully

Please try your hand at a ticket or two, and if you find you enjoy it, I can add you to the project member list.

**Comment by mklemm2** [comment]
> Meanwhile it's just the tickets I feel really guilty about -- it feels really unfair to have people with reasonable easy questions waiting weeks for me to send a 1 liner reply :/

Then I'll start there, to the best of my knowledge.

**Comment by jnwatson** [comment]
I'm definitely interested in more help if you're still interested!
