### ISSUE TITLE
lib/mdb.c not found.

### ISSUE THREAD

**Issue by chanshunli** [jnwatson/py-lmdb#192]
0.94 version：
![6c362419-6c45-4ae9-b1fb-f10c50bd52fd](https://user-images.githubusercontent.com/6021537/51223623-779e9a00-197d-11e9-87e7-5ec56fcd1a03.jpeg)

**Comment by jnwatson** [comment]
The problem isn't that lib/mdb.c isn't found. The problem is that py-lmdb crashed. You can debug this issue by uninstalling the existing python lmdb module, downloading this repository via `git clone`, and then installing the py-lmdb module via `python setup.py build develop`.

That said, that's only useful if you can understand the lmdb C source code.

Can you post the aaa.py source code, or even better, a minimal subset that crashes? What version of lmdb is this?

**Comment by jnwatson** [comment]
Closing due to lack of response. Feel free to reopen.
