### ISSUE TITLE
Ensure that single database is opened per process

### ISSUE THREAD

**Issue by nirs** [jnwatson/py-lmdb#193]
LMBD requires that database is opened exactly once per process. Opening multiple times breaks
file locks silently, which leads to corrupting the database.

The current way to ensure this is to create a global env in the module level, but this means importing
a module has side effects, which is anti pattern. This also make it harder to test code using lmdb, since
you need to modify the module global state from the tests.

This can be solved by keeping the internal MDB_env in the module, and ensure that only single instance
can be create for the same database path.

The internal instance can be closed when the last Environment object is closed. This can also help to 
handle state readers.

## Suggested API:

Open database:

    env1 = lmdb.open(path)

Open same database from another thread:

    env2 = lmdb.open(path)
  
env1 and env2 reference the same internal MDB_env.

Closing env:

    env1.close()

Decrease reference count on internal env, and mark this instance as closed.

    env2.close()

Actually close the internal instance.

This will eliminate the need to implement this user code:
https://github.com/nirs/vdsm/blob/6a5ad07c1a9f7b5e7d649d48c320bbd1219f4d92/lib/vdsm/storage/managedvolumedb.py#L117

**Comment by dw** [comment]
I looked at doing this quite extensively a few years ago, but it is in general unsolvable, which is why LMDB itself doesn't handle it. I'm still happy to reinvestigate "doing something", but I'll need to go reading old logs to figure out why this one got rejected - it was due to a strong recommendation from upstream and it as I recall it had a sound basis.

Off the top of my head right now:

- deduplicating Environment objects says nothing about handling of their varying flags
- dedupping is only possible for Python env objects, an in-process C lib using LMDB has the same problem. A few consuming apps actually follow this pattern
- upstream flat out refuse to have any global state in their library whatsoever, so this will never be implemented upstream
- "The current way to ensure this is to create a global env in the module level, but this means importing
a module has side effects, which is anti pattern" -> solution in the binding only moves the global to a new place, it still exists

These aren't the real reason though. I need to go dig in my logs. Thanks for reporting

**Comment by nirs** [comment]
@dw, Right, this cannot be done in lmbd.Environment level because of the arguments, so it seems that 
this must be solved at the application level.

What we can do now is:

1. Add this warning from http://www.lmdb.tech/doc/index.html:

    Do not have open an LMDB database twice in the same process at the same time.
    Not even from a plain open() call - close()ing it breaks flock() advisory locking.

It should be translated to lmbd bindings and python terms.

2. Add example code (or tests) for using env with multiple threads

**Comment by jnwatson** [comment]
Thank for for your suggestion. I have added a warning to the documentation.

The multiple thread issue hasn't really been a problem for me (though now I mostly use async). One thread (usually the main) is responsible for set up and tear down, and doesn't tear anything down until all the threads are done. This is important because there's a race at close too. If you try to write and another thread closes the environment, it can crash.
