### ISSUE TITLE
Question: What about binding for MDBX (revised and extended descendant of LMDB)?

### ISSUE THREAD

**Issue by leo-yuriev** [jnwatson/py-lmdb#204]
intro: [libmdbx](https://github.com/leo-yuriev/libmdbx) is revised and extended descendant of Symas LMDB with a [set of noticeable improvements and extensions](https://github.com/leo-yuriev/libmdbx#improvements-over-lmdb), but currently supports only Linux and Windows.

In the near future, I plan to add Python bindings for MDBX and then maybe for [libfpta](https://github.com/leo-yuriev/libfpta). Using _py-lmdb_ for this as the basis looks like a reasonable start.

In this regard, I would like to know your wishes and receive your advices, if any will be. I would also like to discuss the question - whether I should make a separate fork or focus on the subsequent merge-in to the your project.

Regards.

**Comment by oddjobz** [comment]
@leo-yuriev I've just had a quick look at mdbx, not seen it before, but it looks cool. Speaking purely as a user, if py-lmdb had the ability to use either lmdb or mdbx as a back-end it would certainly encourage current py-lmdb users to give mdbx a try. Is the mdbx API sufficiently similar to lmdb to make having a single python binding practical?

**Comment by jnwatson** [comment]
Thanks for reaching out. I've seen your stuff before. It looks really interesting.
I see advantages and disadvantages of sharing the same library for both.
Pro:
- Any bugs that are fixed in py-lmdb will apply to both back ends.
- The more the merrier!

Cons:
- You'll be mostly tied to the existing lmdb API. There are some sharp bits I'd change given a chance, but this library API is mostly modeled directly on the lmdb C API. If you come up with a different API, it would be tricky to maintain a coherent single Python library API.
- Testing would get a bit more complicated. Adding a dimension to the test matrix is not something to take lightly (we already have OS, Python version, and CFFI vs. C dimensions).
- Installation might get a bit more complicated. We have to consider whether the installed python module would have both libraries by default, or whether we would require the bracket syntax e.g. `pip install splinter[django]`.

**Comment by leo-yuriev** [comment]
The MDBX API is 90-95% compatible with LMDB, but the remaining 5% seems will confuse users in case both bindings be combined into single library. With all the other arguments, I think it's reasonable to make a separate library.

However, I will (most likely) provide functions to emulate the py-lmdb interface, or also some interface faсade to choose between lmdb and mdbx.
